env:
  browser: true
  es6: true
  node: true
  vue/setup-compiler-macros: true
extends:
  - airbnb-base
  - plugin:vue/vue3-recommended
  - prettier
globals:
  chrome: true
parser: vue-eslint-parser
parserOptions:
  parser: "@babel/eslint-parser"
  requireConfigFile: false
#   sourceType: module
rules:
  no-restricted-globals:
    - off
  import/prefer-default-export:
    - off
  import/extensions:
    - off
  func-names:
    - off
  no-nested-ternary:
    - off
  no-multi-assign:
    - off
  no-throw-literal:
    - off
  no-underscore-dangle:
    - off
  no-param-reassign:
    - error
    - props: false
  no-shadow:
    - error
    - allow:
        - state
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  # parcel support
  import/no-absolute-path:
    - off
  import/no-unresolved:
    - off
  # experiment
  complexity:
    - off
    - 11
  vue/multi-word-component-names:
    - off