extends:
  - stylelint-config-recommended-vue
  - stylelint-config-recommended-vue/scss
  - stylelint-config-recommended-scss
  - stylelint-config-prettier
customSyntax: postcss-html
rules:
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
        - v-deep